#!/usr/bin/env bash

PICTURE=/tmp/i3lock.png
# SCREENSHOT="scrot -z $PICTURE"

BLUR="5x4"

# $SCREENSHOT
# convert $PICTURE -blur $BLUR $PICTURE
# convert $PICTURE -scale 2% -scale 5000% $PICTURE
i3lock -i $HOME/.config/awesome/theme/wallpaper.png
# rm $PICTURE
